on:
  push:
    branches:
      - main

jobs:
  cli_client_integration:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install.sh
      - run: ./scripts/build.sh test -Dtest-filter="client.zig:"
      - run: ./scripts/build.sh cli_client_integration
      - run: ./zig-out/bin/cli_client_integration
